# Generated by Django 4.1.3 on 2023-08-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='test',
        ),
    ]
