# Generated by Django 4.1.3 on 2023-08-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.category'),
            preserve_default=False,
        ),
    ]
